version: '3.9'

services:


  searchword:
    container_name: notepluse
    build:
      context: .
      dockerfile: Dockerfile
 
    environment:
      - SECRET_KEY1="qwertyuiopasdfghjklzxcvbnmgenratedfjsdfjs"

    volumes:
      - .:/usr/src/app

    ports:  
      - "8000:80"